
// Posts
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
export const GET_POSTS_LOADING = 'GET_POST_LOADING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';

// Comments
export const GET_COMMENTS_LOADING = 'GET_COMMENTS_LOADING';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';

// Profile
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_LOADING = 'GET_PROFILE_LOADING';

// Auth
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
